import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Orkhan Aliyev Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen overflow-scroll hide-scrollbar border-[22px] border-[#EDEDED]">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
